services:
  api:
    container_name: knowledge-management-api
    build:
      dockerfile: apps/api/Dockerfile
      context: .
    ports:
      - "3000:3000"
  db:
    container_name: knowledge-management-database
    image: postgres:17.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: knowledge_management
      POSTGRES_USER: knowledge_management
      POSTGRES_PASSWORD: knowledge_management
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db:
