version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=knowledge_management
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - knowledge_management_network
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./infra/docker/api/Dockerfile
    restart: always
    depends_on:
      - postgres
    ports:
      - 3000:3000
    networks:
      - knowledge_management_network

volumes:
  postgres_data:

networks:
  knowledge_management_network:
    external: true